# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MetaGAM Constants
                                 A QGIS plugin
 Plugin qui permet de gérer les métadonnées uniques à la métropole de Grenoble.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-12-20
        git sha              : $Format:%H$
        copyright            : (C) 2022-2025 by Service SIT - Amr HAMADEH, Steven PION-ROUX
                             : camptocamp - Moritz KIRMSE
        email                : demande_sit@grenoblealpesmetropole.fr
 ***************************************************************************/

/***************************************************************************
 *                               h                                          *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
LICENCE_OUVERTE_OD = "Licence ouverte (OpenDATA)"
LICENCE_FERMEE = "Licence fermée (Uniquement en interne)"

THEMES_INSPIRE = "Thèmes INSPIRE"
