# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MetaGAM Fentere Message
                                 A QGIS plugin
 Plugin qui permet de gérer les métadonnées uniques à la métropole de Grenoble.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-12-20
        git sha              : $Format:%H$
        copyright            : (C) 2022-2025 by Service SIT - Amr HAMADEH, Steven PION-ROUX
        email                : demande_sit@grenoblealpesmetropole.fr
 ***************************************************************************/

/***************************************************************************
 *                               h                                          *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/

module for dockable text widget
"""

from PyQt5 import QtWidgets
from qgis.PyQt.QtWidgets import QDockWidget


class TextDockWidget(QDockWidget):  # pylint: disable=too-few-public-methods
    """
    dockable text widget
    """

    def __init__(self, parent=None):
        super().__init__(parent)

        self.setWindowTitle("Mon dockwidget texte")
        self.text_widget = QtWidgets.QWidget()
        self.text_layout = QtWidgets.QVBoxLayout()
        self.text_label = QtWidgets.QLabel("Texte à afficher")
        self.text_layout.addWidget(self.text_label)
        self.text_widget.setLayout(self.text_layout)
        self.setWidget(self.text_widget)
