stages:
  - pyStage
  - monstage

job-1:
  stage: monstage
  tags:
    - qgistest
  script:
    - docker images

job-linter:
  stage: pyStage
  image: qgis-server
  tags:
    - qgistest
  script:
    - apt install python3-pip
    - pip install pylint
    - python3 -m pylint TestPy.py
 