stages:
  - pyStage
  - monstage


before_script:
  - unset http_proxy 
  - unset https_proxy
  - cp /etc/gitlab-runner/certs/* /usr/local/share/ca-certificates
  - update-ca-certificates
  - export REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
 # - apt-get update -y && apt-get install -y sshpass python3-pip

job-1:
  stage: monstage
  tags:
    - qgistest
  script:
    - docker images

job-linter:
  stage: pyStage
  image: qgis-server
  tags:
    - qgistest
  script:
   # - pip install pylint
    #- python3 -m pylint TestPy.py
    - docker run qgis-server ./TestPy.py
 