# This file is a template, and might need editing before it works on your project.
# This is a sample GitLab CI/CD configuration file that should run without any modifications.
# It demonstrates a basic 3 stage CI/CD pipeline. Instead of real tests or scripts,
# it uses echo commands to simulate the pipeline execution.
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages
#
# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
#
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml

variables:
  POSTGRES_USER: geonetwork
  POSTGRES_PASSWORD: geonetwork
  POSTGRES_DB: geonetwork
  PGHOST: database
  PGDATABASE: sig
  PGUSER: geonetwork
  PGPASSWORD: geonetwork


stages:          # List of stages for jobs, and their order of execution
  - docker
  - lint

install-lint-base-runner:
  stage: lint
  script:
    - cat /etc/issue
    - apt update
    - apt install -y python3-venv git
    - python3 -m venv /venv
    - /venv/bin/pip install pre-commit
    - /venv/bin/pre-commit -V
    - echo "Linting code... This will take about 10 seconds."
    - /venv/bin/pre-commit run --all-files
    - echo "No lint issues found."

run-docker-compo:
  stage: docker
  image: qgis/qgis:release-3_16
  services:
    - name: postgis/postgis:12-2.5
      alias: database
  variables:
    DOCKER_HOST: "tcp://docker:2375"
  script:
    - apt update
    - apt install -y libqt5sql5-psql
    - pip install nose requests_mock
    - psql -d geonetwork -f ./postgres/sql/01_db_xsmall_hydre.sql
    - cd meta_gam
    - export PGSERVICEFILE=../qgis/pg_service.conf
    - export GN_URL=http://geonetwork:8080/geonetwork
    # skip tests which depend on a running local geonetwork server
    - export TEST_SELECTOR='-a !localGN'
    - xvfb-run make test
