stages:
  - pyStage
  - monstage

job-1:
  stage: monstage
  script:
    - ./test.sh
  rules:
    - when: always

job-linter:
  stage: pyStage
  tags:
    - qgistest
  script:
    - python3 -m pylint TestPy.py
  rules:
    - when: always
