stages:
  - pyStage
  - monstage

job-1:
  stage: monstage
  tags:
    - qgistest
  script:
    - docker images

job-linter:
  stage: pyStage
  image: python:latest
  tags:
    - qgistest
  script:
    - pip install pylint
    - python3 -m pylint TestPy.py
 