stages:
  - pyStage
  - monstage

job-1:
  stage: monstage
  image: python:latest
  tags:
    - qgistest
  script:
    - ./test.sh

job-linter:
  stage: pyStage
  image: python:latest
  tags:
    - qgistest
  script:
    - python -m pylint TestPy.py


