stages:
  - pyStage
  - monstage

job-1:
  stage: monstage
  image: python:3.7
  script:
    - ./test.sh
  rules:
    - when: always

job-linter:
  stage: pyStage
  image: python:latest
  script:
    - apt-get update && apt-get install -y pylint
    - pylint TestPy.py
  rules:
    - when: always

job-testunit:
  stage: monstage
  image:
    name: qgis/qgis:latest
    entrypoint: [ '/bin/bash', '-c', 'ln -snf /bin/bash /bin/sh && /bin/bash -c $0' ]
  services:
    - name: python:3.7
  script:
    - python -m unittest TestPy.py
  rules:
    - when: always
