stages:
  - Geonetwork_stage


before_script:
  - unset http_proxy 
  - unset https_proxy
  - export REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
  - sudo apt-get update -y && sudo apt-get install -y sshpass python3-pip

job-unitTest_geonetwork:
  stage: Geonetwork_stage
  image: qgisservergam:latest
  tags:
    - qgistest
  script:
    - python3 -m unittest $CI_PROJECT_DIR/meta_gam/test/geonetworkTest.py
 