stages:
  - pyStage
  - monstage

job-1:
  stage: monstage
  image: qgis:latest
  script:
    - ./test.sh
  rules:
    - when: always

job-linter:
  stage: pyStage
  image: qgis:latest
  script:
    - python3 -m pylint TestPy.py
  rules:
    - when: always
