stages:
  - pyStage
  - monstage

job-1:
  stage: monstage
  image: python:latest
  tags:
    - qgistest
  script:
    - /bin/sh -c "./test.sh"

job-linter:
  stage: pyStage
  image: python:latest
  tags:
    - qgistest
  script:
    - /bin/sh -c "python3 -m pylint TestPy.py"
