stages:
  - pyStage
  - monstage

job-1:
  stage: monstage
  tags:
    - qgistest
  script:
    - ./test.sh

job-linter:
  stage: pyStage
  tags:
    - qgistest
  script:
    - python3 -m pylint TestPy.py

